"""empty message

Revision ID: 5310d9bda2e0
Revises: 11d5916f1efd
Create Date: 2017-12-19 22:49:12.586000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5310d9bda2e0'
down_revision = '11d5916f1efd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_follows_timestamp', table_name='follows')
    op.drop_column('follows', 'timestamp')
    op.drop_column('follows', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follows', sa.Column('id', mysql.INTEGER(display_width=11), nullable=False))
    op.add_column('follows', sa.Column('timestamp', mysql.DATETIME(), nullable=True))
    op.create_index('ix_follows_timestamp', 'follows', ['timestamp'], unique=False)
    # ### end Alembic commands ###
